from commands.start import cmd_start
from commands.help import cmd_help
from commands.add import cmd_add
from commands.ip import cmd_ip
from commands.restart import cmd_re
from commands.ssh import cmd_ssh
from commands.exit import cmd_exit
from commands.stats import cmd_stats
from commands.la import cmd_la